### ISSUE TITLE
Dumping the AD for import into Bloodhound fails using low priv. accounts in 2.0.4

### ISSUE THREAD

**Issue by jsdhasfedssad** [ly4k/Certipy#29]
I can successfully dump my AD for import into Bloodhound using 2.0.1 and a low .priv account.
<img width="427" alt="dump_working" src="https://user-images.githubusercontent.com/97032878/155145361-d9c5580d-1ad7-4997-8fc5-5745d2e85b0a.png">

When I try this in 2.0.4 using the same low priv. account as above and the same AD this partially fails.
<img width="553" alt="dump_failing" src="https://user-images.githubusercontent.com/97032878/155145391-31a3cbd9-9c98-41dd-9643-630993046bef.png">

When I use the account domainadmin1 (high priv.) dumping works in 2.0.4. 
<img width="429" alt="dump_working2" src="https://user-images.githubusercontent.com/97032878/155146385-05409bad-b2a4-4767-a6dc-2b9d92526e68.png">

Is all of this intentionally? If not something seems to have broken.

**Comment by ly4k** [comment]
Should be fixed in 2.0.5. Can you please verify?

**Comment by jsdhasfedssad** [comment]
Great! Assuming the error below is just temporary until the backup feature runs, this works in 2.0.6.
![dump_working3](https://user-images.githubusercontent.com/97032878/155287237-d99e2976-1ee9-4382-b634-a48ded16a0b4.png)

**Comment by ly4k** [comment]
Yes, so the new version tries both methods. The MS-CSRA method is faster when the Remote Registry service isn't running, but apparently that method behaves differently in regards to permissions, probably because of DCOM. So yes, the output is a bit verbose if MS-CSRA fails. Perhaps I could print it only in verbose (-debug) mode :)
