### ISSUE TITLE
"UnboundLocalError: local variable 'tgt' referenced before assignment" error when requesting a TGT for the Kerberos account KRBTGT

### ISSUE THREAD

**Issue by jsdhasfeds** [ly4k/Certipy#3]
Hi,

At the top of the below screenshot you can see a successful request for a certificate for the Kerberos account KRBTGT. However, when attempting to authenticate using that certificate in order to get the NT hash of the account, the error "UnboundLocalError: local variable 'tgt' referenced before assignment" occurs.

At the bottom of the screenshot you see the same but for the account Administrator which works.

It would be nice to be able to target the Kerberos account since that is typically less monitored and its password is typically rarely changed.

Thanks!

![image](https://user-images.githubusercontent.com/67747680/136976044-e9528691-28a1-4d20-b6dd-57ab4b8b9899.png)

**Comment by ollypwn** [comment]
Also, a password change won't affect your certificate. Your certificate will still work for authentication, even if the password is changed. Only when the certificate is revoked or expired will it no longer work. I would simply target a domain administrator, and if you want the KRBTGT account, you could extract the hash from here.

**Comment by ollypwn** [comment]
Yes, it's possible to request the certificate. But when requesting a TGT using the certificate, you'll get an error. It's also possible to request certificates for disabled and non-existing accounts, but it's not possible to get a TGT for these accounts as well.

Your issue is fixed in #ce7ee7cdcbaf12f86d28179bd8a61808498f06cd
