### ISSUE TITLE
Distinguished Names longer than 64 characters breaks Shadow Credentials

### ISSUE THREAD

**Issue by carlneuhaus** [ly4k/Certipy#63]
When requesting Shadow Credentials, Certify will encode the user's DN in the Subject of the generated x509 certificate. According to standard, the Subject must not be longer than 64 characters. User accounts may be buried deep in the Domain and therefore their DN will be longer than 64 characters.

It is possible to get around this issue by using the SubjectAlternativeName field with the user's UPN as a DNS name. 

It appears this issue is similar to others such as #62 however since the `shadow.py` functions utilise the `dsinternal` library the fixes do not work. 

One janky workaround I have found is patching the `__init__.py` function in `dsinternals/common/cryptography/X509Certificate2.py`
```
...
extensions = []
san_list = ["DNS:long_user_name@longdomainname.example.com"]
extensions.append(OpenSSL.crypto.X509Extension(b'subjectAltName', False, ','.join(san_list).encode()))
self.certificate.add_extensions(extensions)
...
```

**Comment by ly4k** [comment]
Hello @carlneuhaus This issue is related to #40. I have fixed this is new upcoming release of Certipy which will be published this weekend. It will not be possible to get around this issue with SAN since SAN and Subject are two different things in the certificate. The SAN is an extension that can include a UPN or DNS name for instance, whereas the Subject is usually in the same form as the DN. The Subject doesn't really matter, and the fix will just cut the Subject if it's too long :-)

**Comment by ly4k** [comment]
Fixed in https://github.com/ly4k/Certipy/commit/defd7f458d8287ed4dc72c5d3164e507d2df3bd9
